version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: docker.io/library/postgres:15-alpine
    container_name: hailango-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-HaiLanGo_dev}
      POSTGRES_USER: ${POSTGRES_USER:-HaiLanGo}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-HaiLanGo}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Redis Cache
  redis:
    image: docker.io/library/redis:7-alpine
    container_name: hailango-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
