# HaiLanGo - Terraform Outputs (Simplified)

output "project_id" {
  description = "GCP Project ID"
  value       = var.project_id
}

output "region" {
  description = "GCP Region"
  value       = var.region
}

output "environment" {
  description = "Current environment"
  value       = var.environment
}

output "enabled_apis" {
  description = "List of enabled APIs"
  value       = [for api in google_project_service.apis : api.service]
}

# Summary output
output "setup_summary" {
  description = "Setup summary"
  value = {
    project     = var.project_id
    region      = var.region
    environment = var.environment
    budget      = "$${var.monthly_budget_amount} USD/month"

    console_links = {
      apis       = "https://console.cloud.google.com/apis/dashboard?project=${var.project_id}"
      billing    = "https://console.cloud.google.com/billing?project=${var.project_id}"
      monitoring = "https://console.cloud.google.com/monitoring?project=${var.project_id}"
    }
  }
}

# .env file content generator
output "env_file_content" {
  description = "Content for .env file"
  sensitive   = true
  value       = <<-EOT
    # Google Cloud Configuration
    # Generated by Terraform

    # Project settings
    GOOGLE_CLOUD_PROJECT=${var.project_id}
    GOOGLE_CLOUD_REGION=${var.region}

    # API Key (restricted for client-side use)
    ${var.create_api_keys ? "GOOGLE_CLOUD_API_KEY=${google_apikeys_key.hailango_web_key[0].key_string}" : "# GOOGLE_CLOUD_API_KEY=<not created>"}
  EOT
}
